---
- name: update web, nfs and db servers
  hosts: webservers, nfs 
  remote_user: azureuser
  become: yes
  become_user: root
  tasks:
  - name: delete wireshark
    apt:
      name: wireshark
      state: absent
